# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_concept.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1224, 699)
        MainWindow.setIconSize(QtCore.QSize(22, 22))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-20, 0, 1241, 671))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 461))
        self.stackedWidget.setBaseSize(QtCore.QSize(800, 461))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_20 = QtWidgets.QPushButton(self.page)
        self.pushButton_20.setGeometry(QtCore.QRect(990, 320, 228, 107))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/Desktop/Screenshot_20190902_181407.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon)
        self.pushButton_20.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_33 = QtWidgets.QPushButton(self.page)
        self.pushButton_33.setGeometry(QtCore.QRect(990, 461, 228, 34))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_7 = QtWidgets.QPushButton(self.page)
        self.pushButton_7.setGeometry(QtCore.QRect(757, 179, 227, 107))
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_19 = QtWidgets.QPushButton(self.page)
        self.pushButton_19.setGeometry(QtCore.QRect(990, 179, 228, 107))
        self.pushButton_19.setIcon(icon)
        self.pushButton_19.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_34 = QtWidgets.QPushButton(self.page)
        self.pushButton_34.setGeometry(QtCore.QRect(757, 461, 227, 34))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        self.pushButton_8.setGeometry(QtCore.QRect(757, 320, 227, 107))
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(523, 179, 228, 107))
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setGeometry(QtCore.QRect(274, 179, 243, 107))
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page)
        self.pushButton_6.setGeometry(QtCore.QRect(274, 320, 243, 107))
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_18 = QtWidgets.QPushButton(self.page)
        self.pushButton_18.setGeometry(QtCore.QRect(40, 179, 228, 107))
        self.pushButton_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_18.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_18.setToolTipDuration(-1)
        self.pushButton_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../.designer/backup/Screenshot_20190902_181407.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon1)
        self.pushButton_18.setIconSize(QtCore.QSize(120, 91))
        self.pushButton_18.setAutoRepeatDelay(292)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_17 = QtWidgets.QPushButton(self.page)
        self.pushButton_17.setGeometry(QtCore.QRect(40, 320, 228, 107))
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setIconSize(QtCore.QSize(111, 91))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(523, 320, 228, 107))
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(111, 91))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 80, 542, 196))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 5, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_13.setGeometry(QtCore.QRect(560, 400, 88, 34))
        self.pushButton_13.setObjectName("pushButton_13")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_20.setText(_translate("MainWindow", "Брест"))
        self.pushButton_33.setText(_translate("MainWindow", "Выход"))
        self.pushButton_7.setText(_translate("MainWindow", "Zabbix"))
        self.pushButton_19.setText(_translate("MainWindow", "Bacula"))
        self.pushButton_34.setText(_translate("MainWindow", "Настройки"))
        self.pushButton_8.setText(_translate("MainWindow", "Генератор \n"
" паролей"))
        self.pushButton_4.setText(_translate("MainWindow", "SIEM Комрад"))
        self.pushButton_5.setText(_translate("MainWindow", "ALD"))
        self.pushButton_6.setText(_translate("MainWindow", "Гарантированное  \n"
" стирание"))
        self.pushButton_18.setText(_translate("MainWindow", "KSC"))
        self.pushButton_17.setText(_translate("MainWindow", "DrWeb"))
        self.pushButton.setText(_translate("MainWindow", "JaCarta"))
        self.pushButton_2.setText(_translate("MainWindow", "Изменить"))
        self.label.setText(_translate("MainWindow", "IP-адрес сервера KSC:"))
        self.pushButton_3.setText(_translate("MainWindow", "Изменить"))
        self.label_6.setText(_translate("MainWindow", "IP-адрес сервера Zabbix:"))
        self.label_4.setText(_translate("MainWindow", "IP-адрес сервера SIEM Комрад:"))
        self.pushButton_9.setText(_translate("MainWindow", "Изменить"))
        self.label_8.setText(_translate("MainWindow", "IP-адрес сервера Bacula:"))
        self.pushButton_10.setText(_translate("MainWindow", "Изменить"))
        self.label_10.setText(_translate("MainWindow", "IP-адрес сервера DrWeb:"))
        self.pushButton_11.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_13.setText(_translate("MainWindow", "Назад"))
        self.action.setText(_translate("MainWindow", "Открытие второго окна"))

